import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
bold = { family = "MesloLGM Nerd Font", style = "Bold" }
italic = { family = "MesloLGM Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGM Nerd Font", style = "Bold Italic" }

# Point size of the font
size = 14.0

# Extra spacing per character
[font.offset]
x = 0
y = 0

# Glyph offset (subpixel positioning)
[font.glyph_offset]
x = 0
y = 0